Add optional input notify_on_changed_status

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -14,6 +14,10 @@ inputs:
   github_token:
     description: 'A github token (secrets.GITHUB_TOKEN will suffice)'
     required: true
+  notify_on_changed_status:
+    description: 'Set to a non-empty string to return yes if and only if the status changed'
+    required: false
+    default: ''
 outputs:
   should_send_message:
     description: "`yes|no` depending on if the message should be sent"
@@ -32,13 +36,30 @@ runs:
         last_status=$(curl --silent --header 'authorization: Bearer ${{ inputs.github_token }}' \
                       --header 'content-type: application/json' \
                       "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/runs?per_page=1&status=completed&branch=${{ inputs.branch }}" | jq -r .workflow_runs[0].conclusion)
-        echo "status of the previous build: $last_status"
-        needs_context="${{ inputs.needs_context }}"
-
-        if [[ $(echo $needs_context | grep "result: failure") ]]; then
-          echo "::set-output name=should_send_message::yes"
-        elif [[ $last_status == failure ]]; then
-          echo "::set-output name=should_send_message::yes"
+        if [[  $last_status != success && $last_status != failure ]]; then
+            echo "Invalid \$last_status: $last_status"
+            exit 1
         else
-          echo "::set-output name=should_send_message::no"
+            echo "status of the previous build: $last_status"
+        fi
+        needs_context="${{ inputs.needs_context }}"
+        if [[ $(echo $needs_context | grep "result: failure") ]]; then
+            current_status=failure
+        else
+            current_status=success
+        fi
+        if [[ "${{ inputs.notify_on_changed_status }}" ]]; then
+            if [[ $current_status == $last_status ]]; then
+              echo "::set-output name=should_send_message::no"
+            else
+              echo "::set-output name=should_send_message::yes"
+            fi
+        else
+          if [[ $current_status == failure ]]; then
+            echo "::set-output name=should_send_message::yes"
+          elif [[ $last_status == failure ]]; then
+            echo "::set-output name=should_send_message::yes"
+          else
+            echo "::set-output name=should_send_message::no"
+          fi
         fi
